---
title: "Driver File"
author: "Travis Torline"
---

```{r}
#Load in all necessary information for the analsis

#Begin by loading the packages we'll need
library("extRemes")
library(ncdf4)

#Now, load in the proper sea level data and time vector
ncin <- nc_open("../ncdfFiles/SeaLevelData.nc")

#Here, we multiply by 1000 because we want LSL85 to be in millimeters
LSL85 <- ncvar_get(ncin, "LocalSeaLevel_gamma_RCP85")
LSL85 <- LSL85 * 1000

#Finally, load in a time vector
timeProj <- ncvar_get(ncin, "time_proj")

nc_close(ncin)

#Now, read in all of the CSV files and store them
params1 <- read.csv(file="../parameters_data/Data Frames/params1.csv", header=TRUE, sep=",") #All stationary
params2 <- read.csv(file="../parameters_data/Data Frames/params2.csv", header=TRUE, sep=",") #Mu nonstationary
params3 <- read.csv(file="../parameters_data/Data Frames/params3.csv", header=TRUE, sep=",") #Sigma nonstationary
params4 <- read.csv(file="../parameters_data/Data Frames/params4.csv", header=TRUE, sep=",") #Xi nonstatioanry
params5 <- read.csv(file="../parameters_data/Data Frames/params5.csv", header=TRUE, sep=",") #Sigma/Xi nonstationary
params6 <- read.csv(file="../parameters_data/Data Frames/params6.csv", header=TRUE, sep=",") #Mu/Xi nonstationary
params7 <- read.csv(file="../parameters_data/Data Frames/params7.csv", header=TRUE, sep=",") #Mu/Sigma nonstationary
params8 <- read.csv(file="../parameters_data/Data Frames/params8.csv", header=TRUE, sep=",") #All nonstationary


#The following is code from advisor Tony Wong to read in and normalize historical temperature data from NOAA
#The variables we'll need from this are 'temperature_proj' and 'time_proj'
##=============================================================================
## read_temperature_data.R
##
## read temperature data
## historical from NOAA:
##   NOAA National Centers for Environmental information, Climate at a Glance:
##   Global Time Series, published May 2017, retrieved on June 7, 2017 from
##   http://www.ncdc.noaa.gov/cag/
## future projections from CRNM under RCP8.5, part of CMIP5
##
## Questions? Tony Wong (anthony.e.wong@colorado.edu)
##=============================================================================

# read the projections temperature forcing from CRNM (CMIP5)
# note: these are in K, but going to normalize, so will take a difference and
# it's same as celsius
ncdata <- nc_open('../parameters_data/global.tas.aann.CNRM-CM5.historical+rcp85.r1i1p1.18500101-21001231.nc')
temperature_proj <- ncvar_get(ncdata, 'tas')
time_proj <- ncvar_get(ncdata, 'time')
nc_close(ncdata)

# 'time' on the netcdf ile is YYYYMMDD, where MMDD is July 2 each year (becuase
# of the averaging). so pluck off just the years
time_proj <- floor(time_proj/10000)

# read the historical forcing from NOAA
data.tmp <- read.table('../parameters_data/noaa_temperature_1880-2017.csv', header = TRUE, sep=',')
time_hist <- data.tmp$Year
temperature_hist <- data.tmp$Value

# extend historical back to 1850 with HadCRUT4
data.tmp = read.table('../parameters_data/HadCRUT.4.4.0.0.annual_ns_avg.txt')
time_hadcrut = data.tmp[,1]
temperature_hadcrut = data.tmp[,2]

# normalize all to 1901-2000
ind_norm <- which(time_hist==1901):which(time_hist==2000)
temperature_hist <- temperature_hist - mean(temperature_hist[ind_norm])

ind_norm <- which(time_hadcrut==1901):which(time_hadcrut==2000)
temperature_hadcrut <- temperature_hadcrut - mean(temperature_hadcrut[ind_norm])

ind_norm <- which(time_proj==1901):which(time_proj==2000)
temperature_proj <- temperature_proj - mean(temperature_proj[ind_norm])

# set up the forcing, wherein the historical starts, then projections finish
# 1850-1880 -- hadcrut4
# 1880-2016 -- NOAA historical
# 2017-2100 -- CRNM projection
time_forc <- min(time_hadcrut):max(time_proj)
temperature_forc <- rep(NA, length(time_forc))

ind_hadcrut <- which(time_hadcrut==time_forc[1]):(which(time_hadcrut==time_hist[1])-1)
ind_hist    <- 1:length(time_hist)
ind_proj    <- which(time_proj==(max(time_hist)+1)):which(time_proj==max(time_forc))

temperature_forc <- c(temperature_hadcrut[ind_hadcrut],
                      temperature_hist[ind_hist]      ,
                      temperature_proj[ind_proj]      )

# maximum temperature serves as an additinoal prior constraint on kappa0, kappa1
# that is, kappa1 > -kappa0/Tmax (otherwise, kappa = kappa0 + kappa1*T might be
# negative)  (not necessary for GEV models)
Tmax <- max(temperature_forc)

```

```{r}
#All of the functions that will be necesary for performing the analysis

#The following are used for calculating non-stationary GEV parameters
muNonstat <- function(mu0, mu1, time = 2016){
  newMu <- mu0 + mu1 * temperature_proj[which(time_proj == time)]
}

sigmaNonstat <- function(sigma0, sigma1, time = 2016){
  newSigma <- exp(sigma0 + sigma1 * temperature_proj[which(time_proj == time)])
}

xiNonstat <- function(xi0, xi1, time = 2016){
  newXi <- xi0 + xi1 * temperature_proj[which(time_proj == time)]
}

#THe following is used to create a density distribution for the USACE method
#As inputs, it will take seaLevelData, statParams, nonstatParams timeProj, iterations, yearStart, yearEnd, returnPeriod, uniformStart, and uniformEnd
#seaLevelData = sea level projections IN MILIMETERS
#statParams = stationary GEV parameters IN MILIMETERS
#timeProj = a vector of years for which there is sea level data
#iterations = how many times to go through the above 4 steps
#yearStart = starting year
#yearEnd = ending year
#returnPeriod = The yearly magnitude of the storm (example, a 1 in 100 year storm has a return period of 100)
#uniformStart = the starting number for the uniform distribution
#uniformEnd = the ending number for the uniform distribution

generateUSACE <- function(seaLevelData, statParams, timeProj, iterations = 2064, yearStart = 2016, yearEnd = 2065, returnPeriod = 100, uniformStart = 1.5, uniformEnd = 2){
  
  #Calculate the qevd probability given the return period passed in
  qevdProb = 1 - (1/returnPeriod)
  
  #Create a vector to store the values that we calculate for X'rp
  USACEVector <- c()
  
  
  #We want to go through this process as many times as requested
  for(i in 1:iterations){
    
    #Begin by sampling from the seaLevelData
    #Generate a random index and calculate the change from yearStart to yearEnd
    sampleIndex <- sample(1:ncol(seaLevelData), 1)
    startRow = which(timeProj == yearStart)
    endRow = which(timeProj == yearEnd)
    
    seaLevelChange <- (seaLevelData[endRow, sampleIndex] - seaLevelData[startRow, sampleIndex])
    
    #Now, sample the GEV parameters
    sampleIndex = sample(1:nrow(statParams), 1)
    sampleMu <- statParams[sampleIndex, "u"]
    sampleSigma <- statParams[sampleIndex, "s"]
    sampleXi <- statParams[sampleIndex, "xi"]
  
    #Finally, sample from the uniform distribution to get the surge factor
    surgeFactor <- runif(1, uniformStart, uniformEnd)
    
    #Now, calculate the return level using the sationary parameters sampled above
    returnLevel <- qevd(qevdProb, sampleMu, sampleSigma, sampleXi)
    
    #Modify that value using the sampled surge factor and change in sea level
    returnLevel <- returnLevel + (surgeFactor * seaLevelChange)
    
    #And append the changed value to our vector of values
    USACEVector <- append(USACEVector, returnLevel)
    
  } 
  
  return(USACEVector)
  
}


#A function to get return level distributions from the non-stationary parameters
#parameterSet = A number between 2 and 8 specifying which set of non-stationary parameters to use
#qevdProb = 1 - (1/Return Period)
#yearEnd = the ending year, should match with the generateUSACE Call
getNonstationary <- function(parameterSet = 3, qevdProb = 0.99, yearEnd = 2065){
  
  if(parameterSet == 2){
    nonstatParamsVector <- apply(params2, 1, function(thisRow) qevd(qevdProb, muNonstat(thisRow["u0"], thisRow["u1"], yearEnd), thisRow["s"], thisRow["xi"]))
  }
  else if(parameterSet == 3){
    nonstatParamsVector <- apply(params3, 1, function(thisRow) qevd(qevdProb, thisRow["u"], sigmaNonstat(thisRow["s0"], thisRow["s1"], yearEnd), thisRow["xi"]))
  }
  else if(parameterSet == 4){
    nonstatParamsVector <- apply(params4, 1, function(thisRow) qevd(qevdProb, thisRow["u"], thisRow["s"], xiNonstat(thisRow["xi0"], thisRow["xi1"], yearEnd)))
  }
  else if(parameterSet == 5){
    nonstatParamsVector <- apply(params5, 1, function(thisRow) qevd(qevdProb, thisRow["u"], sigmaNonstat(thisRow["s0"], thisRow["s1"], yearEnd), xiNonstat(thisRow["xi0"], thisRow["xi1"], yearEnd)))
  }
  else if(parameterSet == 6){
    nonstatParamsVector <- apply(params6, 1, function(thisRow) qevd(qevdProb, muNonstat(thisRow["u0"], thisRow["u1"], yearEnd), thisRow["s"], xiNonstat(thisRow["xi0"], thisRow["xi1"], yearEnd)))
  }
  else if(parameterSet == 7){
    nonstatParamsVector <- apply(params7, 1, function(thisRow) qevd(qevdProb, muNonstat(thisRow["u0"], thisRow["u1"], yearEnd), sigmaNonstat(thisRow["s0"], thisRow["s1"], yearEnd), thisRow["xi"]))
  }
  else{
    nonstatParamsVector <- apply(params8, 1, function(thisRow) qevd(qevdProb, muNonstat(thisRow["u0"], thisRow["u1"], yearEnd), sigmaNonstat(thisRow["s0"], thisRow["s1"], yearEnd), xiNonstat(thisRow["xi0"], thisRow["xi1"], yearEnd)))
  }
  
  return(nonstatParamsVector)
  
}
```


```{r}

#Use the functions in order to get the necessary vectors and graph them against one another
USACEDistribution <- generateUSACE(seaLevelData = LSL85, statParams = params1, timeProj = timeProj, iterations = 2064, yearStart = 2016, yearEnd = 2065, returnPeriod = returnPeriod, uniformStart = 1.5, uniformEnd = 2)

nonstationaryDistribution <- getNonstationary(parameterSet = 2, qevdProb = 0.99, yearEnd = 2065)

plot(density(USACEDistribution, from = 0, to = 10000), main = "USACE Density Distribution vs. Non-stationary Parameters Density Distribution", cex.main = 0.97, xlab = "Sea Level [mm]", ylab = "Density", col = "blue")

lines(density(nonstationaryDistribution, from = 0, to = 10000), col = "red")

legend("topright", legend=c("Non-stationary", "USACE"), col=c("red", "blue"), lty=1, cex=0.8, title="Method", text.font=4, bg='lightblue')
```

